version: 2

updates:
  - package-ecosystem: "pip"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/Chicago"

  - package-ecosystem: "pip"
    target-branch: "undetected-chromedriver"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "America/Chicago"
